//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Etickets.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int Id { get; set; }
        public int IdUser { get; set; }
        public int IdBookingMovie { get; set; }
        public System.DateTime BookingDate { get; set; }
        public int Seat { get; set; }
        public string Review { get; set; }
        public Nullable<int> Rating { get; set; }
        public int Status { get; set; }
    
        public virtual BookingMovie BookingMovie { get; set; }
        public virtual User User { get; set; }
    }
}
